version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_strong_Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1433"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - RABBIT_HOST=rabbitmq
    ports:
      - "5000:5000"

  worker:
    build:
      context: ./backend/Kupucha.Worker
      dockerfile: ../../backend/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
