FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Kupucha.Worker/Kupucha.Worker.csproj", "Kupucha.Worker/"]
RUN dotnet restore "Kupucha.Worker/Kupucha.Worker.csproj"
COPY . .
WORKDIR "/src/Kupucha.Worker"
RUN dotnet publish "Kupucha.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Kupucha.Worker.dll"]
